[phases.setup]
nixPkgs = ["bun", "openssl"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bunx prisma generate", "bun run build"]
nixLibs = ["openssl"]

[start]
cmd = "bun run migrate && bun run start"
